# Generated by Django 5.0.7 on 2024-12-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="route_json",
            field=models.JSONField(blank=True, null=True, verbose_name="経路データ（JSON）"),
        ),
    ]
