# Generated by Django 5.0.7 on 2024-12-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0002_confirmation_route_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="bus_route_json",
            field=models.JSONField(blank=True, null=True, verbose_name="バス経路データ（JSON）"),
        ),
    ]
