# Generated by Django 5.0.4 on 2024-12-05 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0003_confirmation_bus_route_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confirmation",
            options={"verbose_name": "住居・身上確認書", "verbose_name_plural": "住居・身上確認書"},
        ),
        migrations.AddField(
            model_name="confirmation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AddField(
            model_name="confirmation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザ",
            ),
        ),
    ]
