# Generated by Django 5.0.4 on 2024-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0004_alter_confirmation_options_confirmation_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="is_bicycle_commute",
            field=models.BooleanField(default=False, verbose_name="自転車通勤"),
        ),
    ]
