# Generated by Django 5.0.4 on 2024-12-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0005_confirmation_is_bicycle_commute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmation",
            name="transportation_type",
            field=models.CharField(
                choices=[("walk", "徒歩"), ("bus", "バス"), ("bicycle", "自転車")],
                default="walk",
                max_length=10,
                verbose_name="最寄駅までの交通手段",
            ),
        ),
    ]
