# Generated by Django 5.0.7 on 2024-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0008_confirmation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="備考"),
        ),
    ]
