# Generated by Django 5.0.7 on 2024-12-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0009_confirmation_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmation",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="備考欄"),
        ),
    ]
