# Generated by Django 5.0.7 on 2024-12-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0010_alter_confirmation_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="commuting_expenses",
            field=models.IntegerField(blank=True, null=True, verbose_name="定期券代"),
        ),
    ]
