# Generated by Django 5.0.7 on 2024-12-26 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0011_confirmation_commuting_expenses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BicycleCommute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("approved", "承認済み"),
                            ("rejected", "差し戻し"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="申請ステータス",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備考欄"),
                ),
                ("application_date", models.DateField(verbose_name="申請日")),
                (
                    "employee_number",
                    models.CharField(max_length=10, verbose_name="社員番号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                ("name_kana", models.CharField(max_length=100, verbose_name="氏名フリガナ")),
                ("affiliation", models.CharField(max_length=100, verbose_name="所属")),
                ("current_address", models.TextField(verbose_name="現住所")),
                ("amount", models.IntegerField(verbose_name="支給金額")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザ",
                    ),
                ),
            ],
            options={
                "verbose_name": "自転車通勤申請書",
                "verbose_name_plural": "自転車通勤申請書",
            },
        ),
    ]
