# Generated by Django 5.0.7 on 2024-12-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0012_bicyclecommute"),
    ]

    operations = [
        migrations.AddField(
            model_name="bicyclecommute",
            name="approval_date",
            field=models.DateField(blank=True, null=True, verbose_name="承認日"),
        ),
        migrations.AddField(
            model_name="confirmation",
            name="approval_date",
            field=models.DateField(blank=True, null=True, verbose_name="承認日"),
        ),
        migrations.AlterField(
            model_name="bicyclecommute",
            name="amount",
            field=models.IntegerField(verbose_name="支給額計"),
        ),
    ]
