# Generated by Django 5.0.7 on 2024-11-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True, verbose_name="入社日"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="employee_type",
            field=models.CharField(
                choices=[("内定者", "内定者"), ("社員", "社員"), ("退職者", "退職者")],
                default="内定者",
                max_length=20,
                verbose_name="社員属性",
            ),
        ),
    ]
