# Generated by Django 5.0.4 on 2025-01-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_employee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_first_login",
            field=models.BooleanField(default=True, verbose_name="初回ログイン"),
        ),
    ]
